### ISSUE TITLE
Commit the /dist folder

### ISSUE THREAD

**Issue by michaelmccombie** [mozilla/protocol-tokens#41]
If we remove /dist for the .gitignore file then the Sketch plugin can pull JSON data directly from Github instead of us having to rely on npm (which requires us to update the Sketch plugin any time a value changes)

**Comment by alexgibson** [comment]
I understand there are some benefits to this change with regard to making the sketch plugin easier to keep up to date, but there are also some inherant disadvantages / risks:

- Developers working on the tokens repo will need to remember to always manually run `gulp` right before making their final commit / merging a PR to the master branch. 
- If this manual step is missed, then there's a risk that we commit incorrect / broken token data to the repo without realising.
- If the sketch plugin pulls from GitHub and not NPM, then there's also a risk that things could break temporarily, due to the master branch being in-flux.
