### ISSUE TITLE
Relationship to Photon

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/protocol-tokens#60]
Would it be possible to document this projects relationship to the [Photon design system](https://design.firefox.com/photon/)?

We're being asked to start using colours from here on a site which is otherwise using Photon colours, so it would be good to understand the overall plans in terms of if Protocol is planned to supersede Photon and any information related to plans around upgrade path if any.

**Comment by reemhamz** [comment]
I know this issue is ~4 years old now, but we just discovered that [Acorn](https://acorn.firefox.com/) is the latest Firefox design system documentation.

Since Photon has ceased and is now Acorn, there's talks between our team to learn more about Acorn by reaching out to the team lead and seeing if there is a role Protocol can play in its growth, or if there'd be a chance to be integrating the two for a multi-brand design system (maybe???).

We'll see how that goes. But for now, I think it's safe to be closing this issue since it's no longer relevant (mostly, anyway).
